### ISSUE TITLE
MSVC++ Windows Library Build

### ISSUE THREAD

**Issue by thiekus** [numediart/MBROLA#12]
Hi, I was doing some experiment to build mbrola windows library using Microsoft Visual C++ toolchains. After some tests, now I was able to build mbrola.dll based from this repo sources, although need little code alteration especially in detection of MSVC compiler to opt-out any ```unistd.h``` headers. Built library can run MBROLA Tools and IndoTTS (Indonesian TTS application) and even possble to build windows 64-bit library (although not tested yet). Some questions:

* There's some references in makefile that's refering into Visual C++ project directory. Could you tell why these Visual C++ projects is excluded in this repo?
* If desired, could I made PR to this repo to include Visual C++ project?

Thanks

**Comment by valdisvi** [comment]
In my opinion, any tool related information should be removed from project (and included in .gitignore file). In open source world there are (too?) many tools, which have to be configured by particular developer who decided to use particular tool. Documentation, though, may include some tips/tricks, which may be necessary to set up particular tool.

**Comment by Mahmood-Taghavi** [comment]
Could you please release the mbrola.dll because it is especially needed for visually impaired users of the espeak speech synthesizer. I hope now that the MBROLA is open-sourced, a non-blocking version of mbrola.dll be available to the community. Because the closed version of mbrola.dll which was available from its web site always block speech synthesis at the first run in each re-start of windows operating system. That blocking to show the MBROLA license produces a huge challenge to the visually impaired users which need speech output to interact with their computer!
Thanks in advance
Mahmood @valdisvi @thiekus

**Comment by thiekus** [comment]
Hi @Mahmood-Taghavi , sorry for late post. I have fork of mbrola that built on Windows using MSVC that drop-in replacement of old mbrola.dll that doesn't nagging everytime you start program that load mbrola library. It made possible because in the fact, macros for MSVC to export that functions is still there. The only missing of this open-source version is project solution that made Windows dll in MSVC. You only need slightly edit some includes, redefine def functions you want to exports, and redefine code files to able build Windows dll. [Use my fork if you interested](https://github.com/thiekus/MBROLA).

You can build using any MSVC version from 6 onwards without problems, even Win64 build is possible and work fine! Or just precompiled binary in the releases page.

**Comment by Mahmood-Taghavi** [comment]
Hi @thiekus 
Thanks for your great job.

**Comment by valdisvi** [comment]
Thanks for contribution, @thiekus!
Can you create pull request with cleaned changes for 3.4-dev -> 3.3 for [Makefile](https://github.com/thiekus/MBROLA/commit/fccec9327a9c80d6e68633d54d5ef5bd0dcee1d0#diff-b67911656ef5d18c4ae36cb6741b7965) and  [common.h](https://github.com/thiekus/MBROLA/commit/fccec9327a9c80d6e68633d54d5ef5bd0dcee1d0#diff-e4975ba9622c295c98a5ffdf6f3b38d4) and [comment](https://github.com/thiekus/MBROLA/commit/fccec9327a9c80d6e68633d54d5ef5bd0dcee1d0#diff-04c6e90faac2675aa89e2176d2eec7d8) adjusted for original project?

**Comment by thiekus** [comment]
Seems this problem have been resolved for now, so I'm closing this...
