### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by muflone** [numediart/MBROLA#16]
Would you please make a tag/release in order to allow GNU/Linux distribution maintainer to package the latest released version, instead of using the old tcts.fpms.ac.be binary files

**Comment by valdisvi** [comment]
I hope, [that is it](https://github.com/numediart/MBROLA/releases/tag/3.3).

**Comment by muflone** [comment]
thank you, Arch Linux has the 3.3 version in the AUR

https://aur.archlinux.org/packages/mbrola/
