### ISSUE TITLE
AGPL License Issues

### ISSUE THREAD

**Issue by thiekus** [numediart/MBROLA#19]
Hi, first of all, I'm actually glad for decision of MBROLA to release their source code to public as open-source. Also, I'm happy to contribute to this project for things what's missing. The only downside of this project is license, reasons:

* AGPL license scope is too broad in my opinion (or often refers as 'viral' license just like GPL). For example, older MBROLA license allows you make program that is proprietary freeware as is for non-commercial and non-military purposes. But in AGPL, linking with it forces you release your entire application per requirements of AGPL license whatever reason your purposes to use while old license does not. It's not even technically direct compatible with GPL v3 as mentioned by [FSF](https://www.gnu.org/licenses/license-list.html#AGPL) while it's still possible by carefully separating module workarounds. In my case, I have closed source, proprietary but non-commercial IndoTTS SDK that ships older mbrola.dll, but for legal reason I could not replace with my build MBROLA library using this AGPL licensed library.
* Diphone database license is sufficent enough to restrict usage of MBROLA to non-commercial and non-military usages. While relicense to LGPL for example, have possibility anyone to use MBROLA library in commercial software, it's seems useless without diphone database. Also, while it's still possible to make their new diphone database, but it's non-trivial task AFAIK. Consider relicense into LGPL license is more make sense in my opinion.
* There also some open-source text to speech synthesizer (not counting with espeak/espeak-ng as it use MBROLA optionally) that have decent output result (less or more than MBROLA in output quality) even with more permissible license. The only reason I stick with MBROLA is obvious: It has Indonesian diphone database. If only I build TTS for more common language like english, I would like to seek elsewhere. Also, the choice of AGPL license is seems unattractive even to open source community due 'viral' nature of this license, so it's obvious why contribution rate to fix MBROLA library is rather lower than other TTS library.

I'm actually doesn't force to relicense into less restrictive LGPL, but I'm hope if is possible. I just try to explain the valid reason for that. Thank you :)

**Comment by valdisvi** [comment]
* Authors of software can choose licenses depending on their goals. If authors want wide usage (even unattributed abuse), they choose weak license like Apache/BSD/etc. If they want encourage collaboration and public development, they choose strong license like AGPL.
AGPL is not problem for [real contributors](https://github.com/numediart/MBROLA/graphs/contributors), and is [not problem, if you use it without modifications](
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)), but, it forces obligations for these who modify it. Just compare rate of development (and fragmentation) of 50 years old BSD-licensed Free/Net/Open/.../*BSD systems (and legal abuse in MacOSX/iOS and time ago in Windows) with "only" 25 years old GPL-licensed Linux.
Particularly to MBROLA, reason might be to encourage [Acapela Group](https://www.acapela-group.com) (which still may be using old, closed source, fork of MBROLA in their projects) switching to open source version and continue collaboration publicly.
* Authors of MBROLA are not authors of MBROLA voices, therefore they cannot legally provide them with different terms. As far as I know, @thierrydutoit asked all authors, to open their license, but didn't get any response. You may contact original authors from [MBROLA-voices](https://github.com/numediart/MBROLA-voices/) page yourself and get their permission for you and everybody.
* Viral licenses are "hard" only if you want to modify code or make derivative work, and hide it. They don't have any limits on your [basic software freedoms](https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Freedoms). You may also try to use other speech engines like HTS, which solves some of problems and introduces their own.

I'm not author of the MBROLA and don't know all the details, how source code of MBROLA was opened, but, hopefully, I explained some for reasons for licensing MBROLA in this way.

**Comment by thierrydutoit** [comment]
Thanks Valdis.
I couldn’t give a better answer.
And I’ll try again to put voices on the git with open lilcenses.
Thierry

De : Valdis Vitolins [mailto:notifications@github.com]
Envoyé : lundi 30 mars 2020 21:15
À : numediart/MBROLA <MBROLA@noreply.github.com>
Cc : Thierry DUTOIT <Thierry.DUTOIT@umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [numediart/MBROLA] AGPL License Issues (#19)


  *   Authors of software can choose licenses depending on their goals. If authors want wide usage (even unattributed abuse), they choose weak license like Apache/BSD/etc. If they want encourage collaboration and public development, they choose strong license like AGPL.
AGPL is not problem for real contributors<https://github.com/numediart/MBROLA/graphs/contributors>, and is not problem, if you use it without modifications<https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)>, but, it forces obligations for these who modify it. Just compare rate of development (and fragmentation) of 50 years old BSD-licensed Free/Net/Open/.../*BSD systems (and legal abuse in MacOSX/iOS and time ago in Windows) with "only" 25 years old GPL-licensed Linux.
Particularly to MBROLA, reason might be to encourage Acapela Group<https://www.acapela-group.com> (which still may be using old, closed source, fork of MBROLA in their projects) switching to open source version and continue collaboration publicly.
  *   Authors of MBROLA are not authors of MBROLA voices, therefore they cannot legally provide them with different terms. As far as I know, @thierrydutoit<https://github.com/thierrydutoit> asked all authors, to open their license, but didn't get any response. You may contact original authors from MBROLA-voices<https://github.com/numediart/MBROLA-voices/> page yourself and get their permission for you and everybody.
  *   Viral licenses are "hard" only if you want to modify code or make derivative work, and hide it. They don't have any limits on your basic software freedoms<https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Freedoms>. You may also try to use other speech engines like HTS, which solves some of problems and introduces their own.

I'm not author of the MBROLA and don't know all the details, how source code of MBROLA was opened, but, hopefully, I explained some for reasons for licensing MBROLA in this way.

**Comment by thiekus** [comment]
Hi @valdisvi @thierrydutoit , thanks for giving insight about license. I understand the decision of choose that license, and I was ok with current AGPL license after that explanations. And yeah, relicensing isn't not easy task either as you should asks to many contributors to agree with new agreement terms. At the last question, could the MBROLA library that built dynamically (as .so or .dll) then I linked from my program, that will use GPLv3? Because the only my main concern was license compatibility.
Sorry for inconvenience...

**Comment by valdisvi** [comment]
I'm not a lawyer, but as far as I know, you can call _external_ AGPL libraries (i.e. with dynamic linking with *.so or *.dll files) from closed source software, but you cannot (legally) compile them _into_ closed source libraries (i.e. with static linking).
Particularly about re-licensing data files, look my comment for [MBROLA-voices license issue](https://github.com/numediart/MBROLA-voices/issues/6#issuecomment-606560302).

**Comment by thiekus** [comment]
Thanks for further explanation! And as was clear, I'm closing this
