### ISSUE TITLE
inquiry wrt project status

### ISSUE THREAD

**Issue by williamh** [numediart/MBROLA#33]
Hi all,

I am the mbrola maintainer for Gentoo Linux.

Someone pointed me to this repository, and I see it has a newer version of mbrola than we have, so I want to confirm.

The last time I touched the package, the home page was http://tcts.fpms.ac.be/synthesis/mbrola.html, and the downloads were on http://tcts.fpms.ac.be/synthesis.

That site is now down, and I don't see anything about this in your documentation, so I need to know if this repository is a fork or the official project.

Thanks for your time, and feel free to close this after you answer.

Thanks,

William

**Comment by valdisvi** [comment]
This is official MBROLA repository.

**Comment by williamh** [comment]
Ok, thanks for the information.
