### ISSUE TITLE
[Question] Using MaryTTS with MBROLA voice to generate machinery voice-overs for a commercial game?

### ISSUE THREAD

**Issue by StepanMynarik** [numediart/MBROLA#37]
Is that possible?

I don't exactly understand the license. We pre-record everything, there will be only resulting wav files shipped with the game.
No TTS engine, no voices. Just the wav files.

We are a small indie game dev team of 2. Using offline TTS engine is perfect, we can re-generate all voiceovers consistently and easily at any time. The TSS community is incredible.

Thank You,
Regards,
Stepan

**Comment by valdisvi** [comment]
This is answered in issue #19.

**Comment by StepanMynarik** [comment]
If I understand it correctly, I can use MBROLA in our use case. There is one thing I have to be wary of though, and that is each specific voice license.

Thanks :)
